"""Admin user-import commit endpoint.

Bulk-creates user accounts from a mapped CSV, seeds a password reset
token per row, and emails the recipient a "set your password" link.

Extracted from ``admin_import.py`` in the 2026-07 refactor.
"""
from __future__ import annotations

import asyncio
import secrets
import uuid
from datetime import UTC, datetime

import bcrypt
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from routes.deps import db, verify_token
from utils.email import send_email

from .helpers import (
    _ai_map_columns,
    _frontend_origin,
    _issue_reset_token,
    _parse_csv,
)

router = APIRouter()
api_router = router


class UserCommitRequest(BaseModel):
    csv_text: str
    column_map: dict[str, str | None] | None = None
    default_role: str = "renter"


@api_router.post("/admin/import/users/commit")
async def commit_user_import(req: UserCommitRequest, payload: dict = Depends(verify_token)) -> dict:
    """Bulk-create users. Each new user gets an autogenerated password
    and a Postmark email containing a "set your password" link."""
    if payload['role'] != 'admin':
        raise HTTPException(status_code=403, detail="Admin access required")

    headers, rows = _parse_csv(req.csv_text)
    if not rows:
        raise HTTPException(status_code=400, detail="No data rows in CSV")

    column_map = req.column_map or await _ai_map_columns(headers, schema="user")

    created: list[dict] = []
    skipped: list[dict] = []

    for i, raw in enumerate(rows, start=1):
        try:
            remapped = {
                column_map.get(k): v for k, v in raw.items()
                if column_map.get(k) is not None
            }
            email = (remapped.get("email") or "").strip().lower()
            name = remapped.get("name") or email
            phone = remapped.get("phone") or ""
            role = (remapped.get("role") or req.default_role).strip().lower()
            if role not in ("renter", "owner", "manager", "admin"):
                role = req.default_role

            if not email:
                skipped.append({"index": i, "error": "Missing email"})
                continue

            existing = await db.users.find_one({"email": email}, {"_id": 0, "id": 1})
            if existing:
                skipped.append({"index": i, "email": email, "error": "Already exists"})
                continue

            tmp_password = secrets.token_urlsafe(20)
            pwd_hash = bcrypt.hashpw(tmp_password.encode(), bcrypt.gensalt()).decode()
            new_user_id = str(uuid.uuid4())
            await db.users.insert_one({
                "id": new_user_id,
                "email": email,
                "password": pwd_hash,
                "name": name,
                "role": role,
                "phone": phone,
                "created_at": datetime.now(UTC).isoformat(),
                "email_verified": True,
                "admin_imported": True,
            })

            raw_token = await _issue_reset_token(new_user_id, email)
            link = f"{_frontend_origin()}/auth/reset-password?token={raw_token}"
            asyncio.create_task(send_email(
                to_email=email,
                subject="Welcome to MyIsraelRental — set your password",
                html_body=(
                    f"<p>Hi {name},</p>"
                    "<p>Your account on <b>MyIsraelRental.com</b> has been created.</p>"
                    f"<p>To activate it, please set your password (link valid 24h):</p>"
                    f"<p><a href=\"{link}\" style='background:#1E6A6A;color:#fff;padding:10px 18px;border-radius:8px;text-decoration:none;'>Set my password</a></p>"
                    f"<p>Or copy and paste: {link}</p>"
                ),
                tag="admin-imported-user",
                skip_suppression_check=True,
            ))
            created.append({"id": new_user_id, "email": email, "role": role})
        except Exception as e:  # noqa: BLE001
            skipped.append({"index": i, "error": f"Unexpected error: {e}"})

    return {
        "summary": {"total": len(rows), "created": len(created), "skipped": len(skipped)},
        "created": created,
        "skipped": skipped,
    }



# --- Quick Add: single property via inline form -------------------------

