import { useEffect, useRef } from 'react';
import { useLocation } from 'react-router-dom';

/**
 * Get everyone onto a new build without them thinking about it.
 *
 * The cache headers are already right: index.html is no-cache and the
 * hashed bundles are immutable, so any RELOAD lands on the newest build.
 * The gap is the person who never reloads — a tab open since this
 * morning keeps running this morning's JavaScript, which is how someone
 * sits on a bug for hours after it was fixed.
 *
 * Two deliberate choices about how the reload happens:
 *
 * It is NOT immediate. Reloading under someone's hands loses whatever
 * they were typing, and this app has a multi-step listing wizard and a
 * chat box. Instead the new build is noted and applied at the next route
 * change — a boundary where, by definition, nobody is mid-sentence.
 *
 * It polls the ASSET MANIFEST, not a version endpoint. The manifest is
 * generated by the build itself and already served no-cache, so there is
 * no version constant for someone to forget to bump — the thing that
 * changes is the thing being compared.
 */
const POLL_MS = 5 * 60 * 1000;

async function currentBuildId() {
  try {
    // cache: 'no-store' as well as the header, because a proxy in front
    // of us is not ours to trust.
    const res = await fetch('/asset-manifest.json', { cache: 'no-store' });
    if (!res.ok) return null;
    const manifest = await res.json();
    // The main bundle's hashed filename IS the build identity.
    return manifest?.files?.['main.js'] || JSON.stringify(manifest?.entrypoints || null);
  } catch {
    // Offline, or the manifest is not served here. Never throw: this is
    // a background nicety and must not surface to anyone.
    return null;
  }
}

export function useBuildRefresh() {
  const location = useLocation();
  const known = useRef(null);
  const stale = useRef(false);

  useEffect(() => {
    let cancelled = false;

    const check = async () => {
      const id = await currentBuildId();
      if (cancelled || !id) return;
      if (known.current === null) {
        known.current = id;
        return;
      }
      if (id !== known.current) stale.current = true;
    };

    check();
    const timer = setInterval(check, POLL_MS);
    // Also on returning to the tab: someone coming back after lunch is
    // exactly who is furthest behind.
    const onVisible = () => { if (document.visibilityState === 'visible') check(); };
    document.addEventListener('visibilitychange', onVisible);

    return () => {
      cancelled = true;
      clearInterval(timer);
      document.removeEventListener('visibilitychange', onVisible);
    };
  }, []);

  // Apply at the next navigation, never mid-page — and never over
  // someone's work.
  useEffect(() => {
    if (!stale.current) return;
    // The listing wizard keeps everything in component state and saves
    // no draft, so a reload there loses the lot. Rather than maintain a
    // list of routes that must be spared and watch it go stale, ask the
    // page directly: is anything typed in and unsaved? A navigation with
    // filled fields still on screen is not a safe moment.
    const dirty = [...document.querySelectorAll('input, textarea')].some((el) => {
      if (el.type === 'file' || el.type === 'hidden' || el.disabled) return false;
      if (el.type === 'checkbox' || el.type === 'radio') return false;
      // A search box someone has typed in is not work worth protecting,
      // but it is cheap to be wrong in this direction: the worst case is
      // the reload waits for one more navigation.
      return String(el.value || '').trim().length > 0;
    });
    if (dirty) return;

    stale.current = false;
    window.location.reload();
  }, [location.pathname]);
}

export default useBuildRefresh;
