"""Generate the MyIsraelRental fillable rental-contract PDF templates.

Called at server startup to (re)generate English and Hebrew blank templates
in /app/backend/uploads/templates/. They're then served via the
/api/contract-template/{lang} endpoint and downloadable from the dashboard.

Design: soft blue/gray palette, clean modern layout, AcroForm text fields so
the landlord or tenant can fill it directly in Acrobat / Preview / browser.
"""
from __future__ import annotations

from pathlib import Path

from reportlab.lib.colors import HexColor, Color
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

try:
    from bidi.algorithm import get_display  # type: ignore
except ImportError:  # pragma: no cover
    def get_display(text: str) -> str:  # fallback: no RTL reordering
        return text

# ---------- Palette ----------
INK = HexColor("#0F172A")      # slate-900, body text
MUTED = HexColor("#64748B")    # slate-500
LINE = HexColor("#CBD5E1")     # slate-300, field underlines
CARD = HexColor("#F8FAFC")     # slate-50, section cards
BORDER = HexColor("#E2E8F0")   # slate-200
BRAND = HexColor("#2563EB")    # blue-600 (soft professional blue)
BRAND_DARK = HexColor("#1E40AF")   # blue-800
ACCENT = HexColor("#0EA5E9")   # sky-500 accent

# ---------- Layout constants ----------
PAGE_W, PAGE_H = A4
MARGIN = 18 * mm

FONTS_DIR = Path(__file__).resolve().parent.parent / "fonts"


def _register_fonts():
    """Register Liberation Sans (bundled) + Noto Hebrew. Idempotent."""
    mappings = [
        ("Inter", "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"),
        ("Inter-Bold", "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"),
        ("Inter-Italic", "/usr/share/fonts/truetype/liberation/LiberationSans-Italic.ttf"),
        ("Hebrew", "/usr/share/fonts/truetype/noto/NotoSansHebrew-Regular.ttf"),
        ("Hebrew-Bold", "/usr/share/fonts/truetype/noto/NotoSansHebrew-Bold.ttf"),
    ]
    for name, path in mappings:
        try:
            if name not in pdfmetrics.getRegisteredFontNames():
                pdfmetrics.registerFont(TTFont(name, path))
        except Exception:
            pass  # font optional — fall back to Helvetica


def _he(text: str) -> str:
    """Reorder Hebrew text for RTL display in a LTR PDF canvas."""
    return get_display(text)


# -----------------------------------------------------------------------------
# English content
# -----------------------------------------------------------------------------
EN = {
    "brand": "MyIsraelRental",
    "brand_tag": "YOUR HOME IN ISRAEL",
    "title": "RENTAL CONTRACT",
    "site": "myisraelrental.com",
    "date": "Date",
    "property": "Property Address",
    "landlord": "Landlord / Sublessor",
    "tenant": "Tenant",
    "name": "Full Name",
    "id": "ID / Passport No.",
    "phone": "Phone",
    "email": "Email",
    "period": "Rental Period",
    "from": "From",
    "to": "To",
    "nights": "Total nights / period",
    "price": "Rental Price",
    "total_amount": "Total Amount",
    "currency": "Currency",
    "deposit": "Security Deposit",
    "deposit_note": "(refundable after checkout, minus any damages)",
    "utilities": "Utilities price",
    "terms": "Terms & Conditions",
    "liability": "Liability",
    "liability_body": (
        "The Tenant is responsible for their safety and belongings. "
        "The Landlord is not liable for any loss, theft, or injury during the rental period."
    ),
    "law": "Governing Law",
    "law_body": "Any disputes shall be resolved by an owner's Rav.",
    "signatures": "Signatures",
    "landlord_sig": "Landlord / Sublessor",
    "tenant_sig": "Tenant",
    "notes": "Inventory / Property Condition Notes (optional)",
    "footer": "Generated by myisraelrental.com",
    "terms_items": [
        "The Tenant agrees to rent the property in its current condition for the agreed period.",
        "The Tenant must keep the property clean, respect neighbors, and avoid causing damage or noise disturbances.",
        "Any damage beyond normal wear and tear will be deducted from the security deposit.",
        "", "", "", "", "", "",
    ],
}

HE = {
    "brand": "MyIsraelRental",
    "brand_tag": _he("הבית שלך בישראל"),
    "title": _he("חוזה שכירות"),
    "site": "myisraelrental.com",
    "date": _he("תאריך"),
    "property": _he("כתובת הנכס"),
    "landlord": _he("משכיר / שוכר משנה"),
    "tenant": _he("שוכר"),
    "name": _he("שם מלא"),
    "id": _he("מספר תעודת זהות / דרכון"),
    "phone": _he("טלפון"),
    "email": _he("דואר אלקטרוני"),
    "period": _he("תקופת השכירות"),
    "from": _he("מתאריך"),
    "to": _he("עד תאריך"),
    "nights": _he("סך הלילות / תקופה"),
    "price": _he("דמי השכירות"),
    "total_amount": _he("סכום כולל"),
    "currency": _he("מטבע"),
    "deposit": _he("פיקדון ביטחון"),
    "deposit_note": _he("(יוחזר לאחר היציאה, בניכוי נזקים ככל שיהיו)"),
    "utilities": _he("עלות שירותים"),
    "terms": _he("תנאים והתניות"),
    "liability": _he("אחריות"),
    "liability_body": _he(
        "השוכר אחראי לבטיחותו ולרכושו האישי. המשכיר אינו אחראי לכל אובדן, גניבה או פגיעה במהלך תקופת השכירות."
    ),
    "law": _he("דין חל"),
    "law_body": _he("כל מחלוקת תוכרע על ידי רב של בעל הבית."),
    "signatures": _he("חתימות"),
    "landlord_sig": _he("משכיר / שוכר משנה"),
    "tenant_sig": _he("שוכר"),
    "notes": _he("הערות מצב הנכס / רשימת מלאי (רשות)"),
    "footer": _he("הופק על ידי myisraelrental.com"),
    "terms_items": [
        _he("השוכר מסכים לשכור את הנכס במצבו הנוכחי לתקופה המוסכמת."),
        _he("על השוכר לשמור על ניקיון הנכס, לכבד את השכנים ולהימנע מגרימת נזק או הפרעות רעש."),
        _he("כל נזק מעבר לבלאי סביר ינוכה מפיקדון הביטחון."),
        "", "", "", "", "", "",
    ],
}


# -----------------------------------------------------------------------------
# Low-level drawing helpers
# -----------------------------------------------------------------------------
def _body_font(rtl: bool) -> tuple[str, str]:
    return ("Hebrew", "Hebrew-Bold") if rtl else ("Inter", "Inter-Bold")


def _draw_header(c: canvas.Canvas, t: dict, rtl: bool):
    # Full-width header band
    c.setFillColor(BRAND_DARK)
    c.rect(0, PAGE_H - 28 * mm, PAGE_W, 28 * mm, fill=1, stroke=0)

    # Lighter accent stripe
    c.setFillColor(ACCENT)
    c.rect(0, PAGE_H - 28 * mm, PAGE_W, 1.5 * mm, fill=1, stroke=0)

    reg, bold = _body_font(rtl)
    # Brand text
    c.setFillColorRGB(1, 1, 1)
    c.setFont(bold, 22)
    c.drawString(MARGIN, PAGE_H - 14 * mm, t["brand"])
    c.setFillColor(HexColor("#93C5FD"))  # blue-300
    c.setFont(reg, 8)
    c.drawString(MARGIN, PAGE_H - 19 * mm, t["brand_tag"])

    # Title on the right
    c.setFillColorRGB(1, 1, 1)
    c.setFont(bold, 16)
    c.drawRightString(PAGE_W - MARGIN, PAGE_H - 14 * mm, t["title"])
    c.setFont(reg, 9)
    c.setFillColor(HexColor("#93C5FD"))
    c.drawRightString(PAGE_W - MARGIN, PAGE_H - 19 * mm, t["site"])


def _draw_footer(c: canvas.Canvas, t: dict, rtl: bool, page_num: int):
    reg, _ = _body_font(rtl)
    c.setFillColor(MUTED)
    c.setFont(reg, 8)
    c.drawCentredString(PAGE_W / 2, 10 * mm, t["footer"])
    c.setFont(reg, 7)
    c.drawRightString(PAGE_W - MARGIN, 10 * mm, f"p. {page_num}")


def _section_header(c: canvas.Canvas, y: float, label: str, rtl: bool) -> float:
    """Bold accent bar + label. Returns next y position."""
    _, bold = _body_font(rtl)
    c.setFillColor(BRAND)
    c.rect(MARGIN, y - 1, 3, 12, fill=1, stroke=0)
    c.setFillColor(INK)
    c.setFont(bold, 11)
    c.drawString(MARGIN + 7, y + 2, label)
    return y - 6


def _label(c: canvas.Canvas, x: float, y: float, text: str, rtl: bool):
    reg, _ = _body_font(rtl)
    c.setFillColor(MUTED)
    c.setFont(reg, 8)
    c.drawString(x, y, text)


def _field(
    c: canvas.Canvas,
    name: str,
    x: float,
    y: float,
    w: float,
    h: float = 9 * mm,
    rtl: bool = False,
    multiline: bool = False,
    font_size: int = 10,
) -> None:
    """Draw an AcroForm text field with a soft underline so it looks
    elegant both blank and filled."""
    reg, _ = _body_font(rtl)
    # Soft underline for the line-look
    c.setStrokeColor(LINE)
    c.setLineWidth(0.7)
    c.line(x, y, x + w, y)
    # Interactive form field (invisible border, sits ON the line)
    try:
        c.acroForm.textfield(
            name=name,
            x=x,
            y=y + 1,
            width=w,
            height=h,
            borderWidth=0,
            fillColor=Color(1, 1, 1, alpha=0),
            textColor=INK,
            fontName=reg,
            fontSize=font_size,
            fieldFlags="multiline" if multiline else "",
            forceBorder=False,
        )
    except Exception:
        pass


# -----------------------------------------------------------------------------
# Page renderer
# -----------------------------------------------------------------------------
def _build_page(c: canvas.Canvas, t: dict, rtl: bool, lang_prefix: str):
    reg, bold = _body_font(rtl)

    _draw_header(c, t, rtl)

    y = PAGE_H - 36 * mm
    col_w = (PAGE_W - 2 * MARGIN - 6 * mm) / 2

    # Date row
    _label(c, MARGIN, y, t["date"], rtl)
    _field(c, f"{lang_prefix}_date", MARGIN + 18 * mm, y - 2, 60 * mm, 8 * mm, rtl=rtl)
    y -= 14 * mm

    # Property Address
    _label(c, MARGIN, y + 4, t["property"], rtl)
    _field(c, f"{lang_prefix}_property_address", MARGIN, y, PAGE_W - 2 * MARGIN, 9 * mm, rtl=rtl)
    y -= 16 * mm

    # -- Landlord section
    y = _section_header(c, y, t["landlord"], rtl)
    y -= 6 * mm
    _label(c, MARGIN, y + 4, t["name"], rtl)
    _field(c, f"{lang_prefix}_ll_name", MARGIN, y, col_w, 8 * mm, rtl=rtl)
    _label(c, MARGIN + col_w + 6 * mm, y + 4, t["id"], rtl)
    _field(c, f"{lang_prefix}_ll_id", MARGIN + col_w + 6 * mm, y, col_w, 8 * mm, rtl=rtl)
    y -= 14 * mm
    _label(c, MARGIN, y + 4, t["phone"], rtl)
    _field(c, f"{lang_prefix}_ll_phone", MARGIN, y, col_w, 8 * mm, rtl=rtl)
    _label(c, MARGIN + col_w + 6 * mm, y + 4, t["email"], rtl)
    _field(c, f"{lang_prefix}_ll_email", MARGIN + col_w + 6 * mm, y, col_w, 8 * mm, rtl=rtl)
    y -= 14 * mm

    # -- Tenant section
    y = _section_header(c, y, t["tenant"], rtl)
    y -= 6 * mm
    _label(c, MARGIN, y + 4, t["name"], rtl)
    _field(c, f"{lang_prefix}_tn_name", MARGIN, y, col_w, 8 * mm, rtl=rtl)
    _label(c, MARGIN + col_w + 6 * mm, y + 4, t["id"], rtl)
    _field(c, f"{lang_prefix}_tn_id", MARGIN + col_w + 6 * mm, y, col_w, 8 * mm, rtl=rtl)
    y -= 14 * mm
    _label(c, MARGIN, y + 4, t["phone"], rtl)
    _field(c, f"{lang_prefix}_tn_phone", MARGIN, y, col_w, 8 * mm, rtl=rtl)
    _label(c, MARGIN + col_w + 6 * mm, y + 4, t["email"], rtl)
    _field(c, f"{lang_prefix}_tn_email", MARGIN + col_w + 6 * mm, y, col_w, 8 * mm, rtl=rtl)
    y -= 14 * mm

    # -- Rental period + price (single card with soft background)
    card_h = 52 * mm
    c.setFillColor(CARD)
    c.setStrokeColor(BORDER)
    c.roundRect(MARGIN, y - card_h + 4, PAGE_W - 2 * MARGIN, card_h, 6, fill=1, stroke=1)

    inner_y = y - 4
    c.setFillColor(INK)
    c.setFont(bold, 10)
    c.drawString(MARGIN + 5 * mm, inner_y, t["period"])
    inner_y -= 9 * mm
    _label(c, MARGIN + 5 * mm, inner_y + 4, t["from"], rtl)
    _field(c, f"{lang_prefix}_from", MARGIN + 5 * mm, inner_y, 45 * mm, 7 * mm, rtl=rtl)
    _label(c, MARGIN + 55 * mm, inner_y + 4, t["to"], rtl)
    _field(c, f"{lang_prefix}_to", MARGIN + 55 * mm, inner_y, 45 * mm, 7 * mm, rtl=rtl)
    _label(c, MARGIN + 110 * mm, inner_y + 4, t["nights"], rtl)
    _field(c, f"{lang_prefix}_nights", MARGIN + 110 * mm, inner_y, 55 * mm, 7 * mm, rtl=rtl)

    inner_y -= 12 * mm
    c.setFillColor(INK)
    c.setFont(bold, 10)
    c.drawString(MARGIN + 5 * mm, inner_y, t["price"])
    inner_y -= 9 * mm
    _label(c, MARGIN + 5 * mm, inner_y + 4, t["total_amount"], rtl)
    _field(c, f"{lang_prefix}_total", MARGIN + 5 * mm, inner_y, 40 * mm, 7 * mm, rtl=rtl)
    _label(c, MARGIN + 50 * mm, inner_y + 4, t["currency"] + " (NIS / USD)", rtl)
    _field(c, f"{lang_prefix}_currency", MARGIN + 50 * mm, inner_y, 25 * mm, 7 * mm, rtl=rtl)
    _label(c, MARGIN + 80 * mm, inner_y + 4, t["deposit"], rtl)
    _field(c, f"{lang_prefix}_deposit", MARGIN + 80 * mm, inner_y, 40 * mm, 7 * mm, rtl=rtl)
    _label(c, MARGIN + 125 * mm, inner_y + 4, t["utilities"], rtl)
    _field(c, f"{lang_prefix}_utilities", MARGIN + 125 * mm, inner_y, 40 * mm, 7 * mm, rtl=rtl)

    # Deposit footnote
    c.setFillColor(MUTED)
    c.setFont(reg, 7)
    c.drawString(MARGIN + 5 * mm, y - card_h + 8, t["deposit_note"])

    y = y - card_h - 6 * mm

    # -- Terms & Conditions
    y = _section_header(c, y, t["terms"], rtl)
    y -= 4 * mm

    c.setFillColor(INK)
    c.setFont(reg, 9)
    for i, item in enumerate(t["terms_items"], start=1):
        # Page-break guard: if we don't have room, flow to the next page first
        needed = 10 * mm if item else 15 * mm
        if y - needed < 30 * mm:
            c.showPage()
            _draw_header(c, t, rtl)
            y = PAGE_H - 36 * mm
            y = _section_header(c, y, t["terms"] + " (continued)", rtl)
            y -= 4 * mm

        # number prefix
        c.setFont(bold, 9)
        c.drawString(MARGIN, y, f"{i}.")
        c.setFont(reg, 9)
        if item:
            # pre-filled text for the 3 first clauses
            c.drawString(MARGIN + 6 * mm, y, item[:120])
            # soft continuation underline — sits one "row" (5mm) below the text
            c.setStrokeColor(LINE)
            c.setLineWidth(0.5)
            c.line(MARGIN + 6 * mm, y - 5 * mm, PAGE_W - MARGIN, y - 5 * mm)
            y -= 10 * mm
        else:
            # Single long underline starting right after the number, like:
            #   4.______________________________________________________
            # _field() draws its own underline + invisible AcroForm textbox,
            # so we don't need to draw an additional line.
            _field(
                c,
                f"{lang_prefix}_term_{i}",
                MARGIN + 6 * mm,
                y - 1.5,
                PAGE_W - 2 * MARGIN - 6 * mm,
                7 * mm,
                rtl=rtl,
                font_size=10,
            )
            y -= 10 * mm

    y -= 2 * mm

    # Start page 2 for liability/signatures if we're running low
    if y < 120 * mm:
        c.showPage()
        _draw_header(c, t, rtl)
        y = PAGE_H - 36 * mm

    # -- Liability
    y = _section_header(c, y, t["liability"], rtl)
    y -= 5 * mm
    c.setFillColor(INK)
    c.setFont(reg, 9)
    # wrap liability body manually (keeps it clean)
    for line in _wrap_text(t["liability_body"], 95):
        c.drawString(MARGIN, y, line)
        y -= 5 * mm
    y -= 3 * mm

    # -- Governing law
    y = _section_header(c, y, t["law"], rtl)
    y -= 5 * mm
    c.setFont(reg, 9)
    c.drawString(MARGIN, y, t["law_body"])
    y -= 10 * mm

    # -- Signatures
    y = _section_header(c, y, t["signatures"], rtl)
    # Give enough vertical room so the "Landlord / Sublessor" label sits BELOW
    # the section header and doesn't overlap it.
    y -= 18 * mm
    sig_w = (PAGE_W - 2 * MARGIN - 10 * mm) / 2

    def _sig_block(x: float, role_label: str, field_prefix: str):
        # Role label sits above the signature line
        c.setFillColor(INK)
        c.setFont(bold, 9)
        c.drawString(x, y + 10 * mm, role_label)
        # Signature line + date line
        c.setStrokeColor(LINE)
        c.setLineWidth(0.8)
        c.line(x, y, x + sig_w * 0.7, y)
        c.line(x + sig_w * 0.72, y, x + sig_w - 2, y)
        # Sub-labels below the lines (with breathing room)
        c.setFillColor(MUTED)
        c.setFont(reg, 8)
        c.drawString(x, y - 4 * mm, "Signature")
        c.drawString(x + sig_w * 0.72, y - 4 * mm, t["date"])
        # Invisible AcroForm text fields over the lines (lets someone type name)
        _field(c, f"{field_prefix}_name", x, y + 0.5, sig_w * 0.68, 7 * mm, rtl=rtl, font_size=10)
        _field(c, f"{field_prefix}_date", x + sig_w * 0.72, y + 0.5, sig_w * 0.26, 7 * mm, rtl=rtl, font_size=10)

    _sig_block(MARGIN, t["landlord_sig"], f"{lang_prefix}_ll_sig")
    _sig_block(MARGIN + sig_w + 10 * mm, t["tenant_sig"], f"{lang_prefix}_tn_sig")

    y -= 18 * mm

    # -- Property Condition / Inventory Notes
    y = _section_header(c, y, t["notes"], rtl)
    y -= 4 * mm
    notes_h = 30 * mm
    c.setFillColor(CARD)
    c.setStrokeColor(BORDER)
    c.roundRect(MARGIN, y - notes_h, PAGE_W - 2 * MARGIN, notes_h, 5, fill=1, stroke=1)
    _field(
        c,
        f"{lang_prefix}_notes",
        MARGIN + 2 * mm,
        y - notes_h + 2 * mm,
        PAGE_W - 2 * MARGIN - 4 * mm,
        notes_h - 4 * mm,
        rtl=rtl,
        multiline=True,
        font_size=9,
    )


def _wrap_text(text: str, max_chars: int) -> list[str]:
    """Very small word-wrapper (avoids reportlab Paragraph for simplicity)."""
    words = text.split()
    lines: list[str] = []
    cur = ""
    for w in words:
        if len(cur) + len(w) + 1 > max_chars:
            lines.append(cur.strip())
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    if cur:
        lines.append(cur)
    return lines


# -----------------------------------------------------------------------------
# Public API
# -----------------------------------------------------------------------------
def generate_template(lang: str, out_path: Path) -> Path:
    """Generate the PDF template for the given language and save it."""
    _register_fonts()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    t = EN if lang == "en" else HE
    rtl = (lang == "he")

    c = canvas.Canvas(str(out_path), pagesize=A4)
    c.setTitle(f"MyIsraelRental Rental Contract ({lang.upper()})")
    c.setAuthor("myisraelrental.com")

    _build_page(c, t, rtl, lang)

    # Apply footer to each page we've drawn
    total_pages = c.getPageNumber()
    _draw_footer(c, t, rtl, total_pages)
    c.save()
    return out_path


def ensure_templates(uploads_root: Path) -> dict[str, Path]:
    """Idempotent helper — call at FastAPI startup."""
    out_dir = uploads_root / "templates"
    results = {}
    for lang in ("en", "he"):
        fname = f"myisraelrental_contract_{lang}.pdf"
        out = out_dir / fname
        if not out.exists():
            generate_template(lang, out)
        results[lang] = out
    return results
